-- =====================================================================
--  Le Chalet de la Grève Blanche — Schéma Supabase
--  À coller dans Supabase > SQL Editor > New query, puis "Run".
--  Le script est ré-exécutable sans risque (idempotent).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. NUITS RÉSERVÉES (le calendrier)
--    Une ligne = une nuit occupée.
-- ---------------------------------------------------------------------
create table if not exists public.bookings (
    date        date primary key,
    note        text,
    created_at  timestamptz not null default now()
);

alter table public.bookings enable row level security;

-- Tout le monde peut LIRE les dates (le calendrier est public)
drop policy if exists "bookings_lecture_publique" on public.bookings;
create policy "bookings_lecture_publique"
    on public.bookings for select
    to anon, authenticated
    using (true);

-- Seul un utilisateur connecté (= le propriétaire) peut ÉCRIRE
drop policy if exists "bookings_ecriture_proprietaire" on public.bookings;
create policy "bookings_ecriture_proprietaire"
    on public.bookings for all
    to authenticated
    using (true)
    with check (true);


-- ---------------------------------------------------------------------
-- 2. DEMANDES DE RÉSERVATION (le formulaire de contact)
--    Écrites uniquement par la fonction serveur (clé service_role),
--    jamais directement par le navigateur.
-- ---------------------------------------------------------------------
create table if not exists public.booking_requests (
    id          uuid primary key default gen_random_uuid(),
    created_at  timestamptz not null default now(),
    nom         text not null,
    email       text not null,
    telephone   text,
    animal      text,
    arrivee     date,
    depart      date,
    adultes     smallint,
    enfants     smallint,
    message     text,
    statut      text not null default 'nouveau',   -- nouveau | traite | archive
    ip_hash     text,
    user_agent  text
);

create index if not exists booking_requests_created_idx
    on public.booking_requests (created_at desc);

alter table public.booking_requests enable row level security;

-- Aucune policy pour anon : le navigateur ne peut ni lire ni écrire.
-- La clé service_role utilisée côté serveur contourne la RLS.
drop policy if exists "demandes_lecture_proprietaire" on public.booking_requests;
create policy "demandes_lecture_proprietaire"
    on public.booking_requests for select
    to authenticated
    using (true);

drop policy if exists "demandes_maj_proprietaire" on public.booking_requests;
create policy "demandes_maj_proprietaire"
    on public.booking_requests for update
    to authenticated
    using (true)
    with check (true);

drop policy if exists "demandes_suppression_proprietaire" on public.booking_requests;
create policy "demandes_suppression_proprietaire"
    on public.booking_requests for delete
    to authenticated
    using (true);


-- ---------------------------------------------------------------------
-- 3. LIVRE D'OR
--    La table existe déjà ; on ne fait que verrouiller les accès.
--    Avant, n'importe qui pouvait insérer un avis depuis le navigateur :
--    c'était une porte ouverte au spam.
-- ---------------------------------------------------------------------
create table if not exists public.reviews (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz not null default now(),
    author      text not null,
    content     text not null,
    rating      smallint not null default 5,
    is_approved boolean not null default false
);

alter table public.reviews enable row level security;

-- Le public ne voit que les avis validés par le propriétaire
drop policy if exists "avis_lecture_publique" on public.reviews;
drop policy if exists "reviews_public_read" on public.reviews;
create policy "avis_lecture_publique"
    on public.reviews for select
    to anon, authenticated
    using (is_approved = true);

-- Plus aucune insertion depuis le navigateur : elle passe par la
-- fonction serveur, qui vérifie d'abord le captcha.
drop policy if exists "avis_insertion_anon" on public.reviews;
drop policy if exists "reviews_public_insert" on public.reviews;

-- Le propriétaire connecté voit et modère tout
drop policy if exists "avis_moderation_proprietaire" on public.reviews;
create policy "avis_moderation_proprietaire"
    on public.reviews for all
    to authenticated
    using (true)
    with check (true);


-- =====================================================================
--  VÉRIFICATION — ces requêtes doivent renvoyer rowsecurity = true
-- =====================================================================
-- select tablename, rowsecurity from pg_tables
--   where schemaname = 'public'
--     and tablename in ('bookings', 'booking_requests', 'reviews');
